runLua("UI_Data/Script/Widget/Enduarance/Endurance_Main.lua")
runLua("UI_Data/Script/Widget/Enduarance/Horse_Endurance_Main.lua")
runLua("UI_Data/Script/Widget/Enduarance/Carriage_Endurance_Main.lua")
runLua("UI_Data/Script/Widget/Enduarance/Ship_Endurance_Main.lua")
runLua("UI_Data/Script/Widget/Enduarance/Weight_Main.lua")
runLua("UI_Data/Script/Widget/Enduarance/Weight_Control.lua")
runLua("UI_Data/Script/Widget/Enduarance/Endurance_Control.lua")
