function FGlobal_Radar_SetColorBlindMode()
end
function FGlobal_Window_Servant_ColorBlindUpdate()
end
function FGlobal_QuestWindowRateSetting()
end
function GameOptionApply_CharacterNameTag_StackHpBar(isShow)
end
function Panel_UIControl_SetShow()
end
