local TestCaseEnum = ServantTestCaseEnum
function PaGlobalFunc_SetServantTestList_Market_A1()
  PaGlobalFunc_ResetServantTestList()
  ToClient_qaCreateItem(1, 0, 100000)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eStableExpansion, true, 17616)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eStableExpansion, true, 17616)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Seal")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUnsealServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eSeal, true)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUnsealServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRemoteSeal, true)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUnsealServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRecoverUnseal, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eSeal, true)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUnsealServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRemoteSeal, true)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRecoverServant, true, 0, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "ChangeTest")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 17576 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eChangeServantName, true, 0, "Changed")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 17938 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eImprintServant, true, 0, true)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 17960 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eChangeForm, true, 0, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 18066 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.ePrimiumChangeForm, true, 0, 2)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eChangeServantLevel, true, 0, 30)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 18386 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eResetServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "DeadCount")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eChangeServantState, true, 0, 5)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReviveServant, true, 0, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eChangeServantDeadCount, true, 0, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 18924 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eResetDeadCount, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Skill")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 18070 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eForgetServantSkill, true, 0, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 17559 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eSkillChange, true, 0, 2, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50123, "Train")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 18440 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/notify 1 0 \235\167\136\234\181\172\234\176\132 \237\133\140\236\138\164\237\138\184\235\165\188 \236\156\132\237\149\180 \236\132\156\235\178\132\236\139\156\234\176\132\236\157\180 \237\152\132\236\158\172 \236\139\156\234\176\132\236\156\188\235\161\156 \235\179\128\234\178\189\235\144\169\235\139\136\235\139\164.")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/addservertime 0 0 0")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eSkillExpTrainStart, true, 0, 18)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/addservertime 0 1 0")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eSkillExpTrainEnd, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/addservertime 0 0 0")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Exchange1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50109, "Exchange2")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eExchangeServant, true, 0, 1, 0, "Exchanged")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, false, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Link")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 51008, "Carriage")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eLinkCarriage, true, 0, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUnLinkCarriage, true, 0, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/changeServantMarketBuyDelayTime 1 1 ")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Market1")
  if ToClient_IsContentsGroupOpen("465") then
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Rent1")
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50109, "Mating1")
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Market2")
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Rent2")
  else
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Market2")
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50109, "Mating")
  end
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegistMarket, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegistMarket, true, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegistMatingMarket, true, 2, 1)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMatingCancle, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegistMatingMarket, true, 2, 0)
  if ToClient_IsContentsGroupOpen("465") then
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegistForRent, true, 3)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRentCancle, true, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegistForRent, true, 3)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegistForRent, true, 4)
  end
end
function PaGlobalFunc_SetServantTestList_Market_B1()
  PaGlobalFunc_ResetServantTestList()
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 1 1000000000")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMarketBuy, true, 0, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Mating2")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMating, true, 0, 0, 0, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 6 1000")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMatingImmediatelyEnd, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReceiveChild, true, 0, "Child")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eUseIngameCommand, true, "/create item 17936 1")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eResetMatingCount, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  if ToClient_IsContentsGroupOpen("465") then
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRentBuy, true, 0, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRentBuy, true, 0, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterForReturn, true, 0)
  end
end
function PaGlobalFunc_SetServantTestList_Market_A2()
  PaGlobalFunc_ResetServantTestList()
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMarektCancle, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMatingPopPrice, true, 0, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMarketPopPrice, true, 0)
  if ToClient_IsContentsGroupOpen("465") then
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRentPopPrice, true, 0, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRentPopPrice, true, 0, 2)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eForcedReturn, true, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReturnBuy, true, 0, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReturnBuy, true, 0, 2)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReleaseServant, true, 0)
  end
end
function PaGlobalFunc_SetServantTestList_Market_B2()
  PaGlobalFunc_ResetServantTestList()
  if ToClient_IsContentsGroupOpen("465") then
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReturnPopPrice, true, 0, 0)
    PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eReturnPopPrice, true, 0, 2)
  end
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Move")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eMoveServant, true, 0, 9, 0)
end
function PaGlobalFunc_SetServantTestList_Market_C()
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eRegisterServant, true, 50139, "Courser")
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eChangeServantLevel, true, 0, 30)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eStartStallionTraining, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eEndStallionTraining, true, 0)
  PaGlobalFunc_InsertServantTestCase(TestCaseEnum.eSellToReward, true, 0)
end
function SetForServantQA()
  ToClient_qaLevelUp(60)
  ToClient_qaCreateItem(1, 0, 1)
  ToClient_qaCreateItem(149003, 0, 1)
  ToClient_qaTeleport(41282, -2886, -45065)
  Proc_ShowMessage_Ack("\235\167\136\234\181\172\234\176\132 \237\133\140\236\138\164\237\138\184 \236\160\132\236\151\144 \237\142\132 \234\176\128\235\176\169 \235\130\180 \235\169\148\236\157\180\235\147\156\235\165\188 \237\134\181\237\149\180 \236\176\189\234\179\160\236\151\144 \236\157\128\237\153\148\235\165\188 \235\132\163\236\150\180\236\163\188\236\132\184\236\154\148")
end
function TeleportStonetail()
  ToClient_qaTeleport(217738, -1702, -1)
end
PaGlobal_ServantTestWaitSecond = 1
function ServantQA1(command)
  PaGlobal_ServantTestRentUserName = command
  PaGlobal_ServantTestName = "ServantQA"
  luaTimer_AddEvent(PrepareServantQA, 0, false, 0, PaGlobalFunc_SetServantTestList_Market_A1)
  luaTimer_AddEvent(PrepareServantQA, 270000, false, 0, PaGlobalFunc_SetServantTestList_Market_A2)
  luaTimer_AddEvent(TeleportStonetail, 300000, false, 0)
end
function ServantQA2(command)
  PaGlobal_ServantTestRentUserName = command
  PaGlobal_ServantTestName = "ServantQA"
  luaTimer_AddEvent(PrepareServantQA, 240000, false, 0, PaGlobalFunc_SetServantTestList_Market_B1)
  luaTimer_AddEvent(PrepareServantQA, 300000, false, 0, PaGlobalFunc_SetServantTestList_Market_B2)
end
function ServantQA3(command)
  PaGlobal_ServantTestRentUserName = command
  PaGlobal_ServantTestName = "ServantQA"
  luaTimer_AddEvent(PrepareServantQA, 0, false, 0, PaGlobalFunc_SetServantTestList_Market_C)
end
