local Mindamage = 0
local Maxdamage = 0
local SumCountDamage = 0
function StartQAequipArmor()
  ToClient_qaDebugDamage(0, 1, 1)
end
function StartQASkillUse(SkillQaNumber)
  ToClient_qaDebugDamage(1, SkillQaNumber)
end
function StartQASkillUseKunoich(ST)
  local selfPlayer = getSelfPlayer()
  if nil == selfPlayer then
    return
  end
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2756)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2160)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2161)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2162)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2128)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1662)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1663)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1664)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1665)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1666)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 949)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 950)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 951)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1624)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1625)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2151)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 991)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 992)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 998)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 943)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 944)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 923)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 924)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 925)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 926)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 931)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 927)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 928)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 929)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 930)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 932)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2154)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2155)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2156)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2157)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 966)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 967)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 968)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 969)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 970)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1626)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1627)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1628)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2135)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2136)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2137)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2138)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2139)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2144)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2121)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2122)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2123)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2124)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 933)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 934)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 935)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 975)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 976)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2125)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2126)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2127)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 977)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 978)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 979)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 958)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 959)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 960)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 961)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2158)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2140)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2141)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2142)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1654)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1655)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1656)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1657)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 1658)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 962)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 963)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 964)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 965)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 988)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 989)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 990)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 953)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 954)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 955)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 956)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 957)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2810)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 701)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 702)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 703)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 704)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2754)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 985)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 986)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 987)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2809)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 696)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 697)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 698)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 699)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3121)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3111)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3123)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3116)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3109)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3108)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3117)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3106)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3101)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3112)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3120)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3119)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3103)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3114)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3110)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3115)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3118)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3113)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3107)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3104)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3105)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3127)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 972)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 973)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 974)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 946)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 947)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 948)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 690)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 691)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 692)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 937)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 938)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 939)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 941)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 942)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2149)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 945)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 952)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2159)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2143)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3692)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3693)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3694)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3731)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3727)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3728)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3729)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3730)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3717)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3718)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3719)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3724)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3725)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3726)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3688)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3689)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3690)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3695)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3691)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3720)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3721)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3722)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 3723)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2145)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2146)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2147)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 2148)
  luaTimer_AddEvent(KunoSkill, 0, false, 0, ST, 999)
  chatting_sendMessage("", "Kunoich SkillTest End(PVP)", CppEnums.ChatType.Private)
end
function KunoSkill(ST, SkillNo)
  if ST == 1 then
    ToClient_qaDebugDamage(1, SkillNo)
  elseif ST == 2 then
  end
end
