local Mindamage = 0
local Maxdamage = 0
local SumCountDamage = 0
function StartQAequipArmor()
  ToClient_qaDebugDamage(0, 1, 1)
end
function StartQASkillUse(SkillQaNumber)
  ToClient_qaDebugDamage(1, SkillQaNumber)
end
function StartQASkillUseWitch(ST)
  local selfPlayer = getSelfPlayer()
  if nil == selfPlayer then
    return
  end
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 846)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 843)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 844)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 845)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 855)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 893)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 894)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 895)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 896)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 897)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 865)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 866)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 867)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 850)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 851)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 852)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 853)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 854)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 827)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 828)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 829)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 830)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 831)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 832)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 833)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2824)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 822)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 823)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 824)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 825)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 826)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 834)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 835)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 836)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 837)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 838)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2823)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 790)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 791)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 792)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 887)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 888)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 889)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 856)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 857)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 858)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 859)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 912)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 913)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 914)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 786)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 787)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 788)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 789)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 877)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 878)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 879)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 880)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 885)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 881)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 882)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 883)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 884)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 886)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3139)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3140)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3144)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3135)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3136)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3133)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3137)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3131)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3141)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3134)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3146)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3130)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3232)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3138)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3132)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3143)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 839)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 840)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 841)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 842)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 818)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 819)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 820)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 821)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 847)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 848)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 849)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3670)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3671)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3672)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3673)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3678)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3679)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3680)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3681)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3685)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3686)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3687)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3646)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3647)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3648)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3649)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3650)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3642)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3643)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3644)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3674)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3675)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3676)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3677)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3651)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3645)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3682)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3683)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 3684)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2186)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2187)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2188)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2189)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2179)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2180)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2181)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2182)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2190)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2191)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2192)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2826)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2197)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2198)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2199)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2825)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2174)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2175)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2176)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2177)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2178)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2165)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2193)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2194)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2195)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2196)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2183)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2184)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2185)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2752)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2203)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2202)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2201)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2207)
  luaTimer_AddEvent(WitSkill, 0, false, 0, ST, 2206)
  chatting_sendMessage("", "Witch SkillTest End(PVP)", CppEnums.ChatType.Private)
end
function WitSkill(ST, SkillNo)
  if ST == 1 then
    ToClient_qaDebugDamage(1, SkillNo)
  elseif ST == 2 then
  end
end
